version: '3'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: seis10
      MYSQL_USER: seis10
      MYSQL_PASSWORD: seis10
      MYSQL_DATABASE: seis10

  api:
    build: .
    depends_on: 
      - db
    # volumes:
    #   - .:/usr/src/app
    ports:
      - 3001:3001
    command: npm run start:prod
    environment:
      DB_HOST: db
